name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: run-test
      run: cd build; export LD_LIBRARY_PATH=$(realpath $(pwd)/src); cd test; ./test1
